// src/react/Child.js
import React from 'react';

import { addTrack } from './TrackContext';

/**
 * https://reactjs.org/docs/react-component.html
 */
export default class Child extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
    addTrack('Child constructor');
  }
  static getDerivedStateFromProps() {
    addTrack('Child getDerivedStateFromProps');
    return null;
  }
  componentDidMount() {
    addTrack('Child componentDidMount');
  }
  componentWillUnmount() {
    addTrack('Child componentWillUnmount');
  }
  getSnapshotBeforeUpdate() {
    addTrack('Child getSnapshotBeforeUpdate');
    return null;
  }
  componentDidUpdate() {
    addTrack('Child componentDidUpdate');
  }
  shouldComponentUpdate() {
    addTrack('Child shouldComponentUpdate');
    return true;
  }
  render() {
    addTrack('Child render');

    return (
      <div style={Style.child}>
        <div style={Style.text}>{`Child - ${this.props.count}`}</div>
      </div>
    );
  }
}

const Style = {
  child: {
    position: 'relative',
    width: 100,
    height: 100,
    border: '3px solid orange',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  text: {
    position: 'absolute',
    top: 0,
    left: 0
  }
};

// src/vue/Child.vue
<template>
  <div class="child">
    <div class="text">{{ text }}</div>
  </div>
</template>

<script>
import { addTrack } from './TrackContext';

export default {
  name: 'Child',
  props: ['count'],
  data() {
    return {};
  },
  computed: {
    text() {
      return `Child - ${this.count}`;
    }
  },
  beforeCreate() {
    addTrack('Child beforeCreate');
  },
  created() {
    addTrack('Child created');
  },
  beforeMount() {
    addTrack('Child beforeMount');
  },
  mounted() {
    addTrack('Child mounted');
  },
  beforeUpdate() {
    addTrack('Child beforeUpdate');
  },
  updated() {
    addTrack('Child updated');
  }
}
</script>

<style scoped>
.child {
  position: relative;
  width: 100px;
  height: 100px;
  border: 3px solid orange;
  display: flex;
  align-items: center;
  justify-content: center;
}
.text {
  position: absolute;
  top: 0;
  left: 0;
}
</style>
