// src/react/Parent.js
import React from 'react';

import Child from './Child';

import { addTrack } from './TrackContext';

/**
 * https://reactjs.org/docs/react-component.html
 */
export default class Parent extends React.Component {
  constructor(props) {
    super(props);
    this.state = {};
    addTrack('Parent constructor');
  }
  static getDerivedStateFromProps() {
    addTrack('Parent getDerivedStateFromProps');
    return null;
  }
  componentDidMount() {
    addTrack('Parent componentDidMount');
  }
  componentWillUnmount() {
    addTrack('Parent componentWillUnmount');
  }
  getSnapshotBeforeUpdate() {
    addTrack('Parent getSnapshotBeforeUpdate');
    return null;
  }
  componentDidUpdate() {
    addTrack('Parent componentDidUpdate');
  }
  shouldComponentUpdate() {
    addTrack('Parent shouldComponentUpdate');

    if (this.props.count > 3) {
      return false;
    }
    return true;
  }
  render() {
    addTrack('Parent render');
    return (
      <div style={Style.parent}>
        <div style={Style.text}>{`Parent - ${this.props.count}`}</div>
        <Child count={this.props.count}/>
      </div>
    );
  }
}

const Style = {
  parent: {
    position: 'relative',
    width: 200,
    height: 200,
    border: '3px solid blue',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center'
  },
  text: {
    position: 'absolute',
    top: 0,
    left: 0
  }
};

// src/vue/Parent.vue
<template>
  <div class="parent">
    <div class="text">{{ text }}</div>
    <Child :count="count"/>
  </div>
</template>

<script>
import Child from './Child.vue';

import { addTrack } from './TrackContext';

export default {
  name: 'Parent',
  props: ['count'],
  components: {
    Child,
  },
  data() {
    return {
      text: `Parent - ${this.count}`
    };
  },
  watch: {
    count(val, oldVal) {
      if (val > 4) {
        return;
      }
      this.text = `Parent - ${val}`;
    }
  },
  beforeCreate() {
    addTrack('Parent beforeCreate');
  },
  created() {
    addTrack('Parent created');
  },
  beforeMount() {
    addTrack('Parent beforeMount');
  },
  mounted() {
    addTrack('Parent mounted');
  },
  beforeUpdate() {
    addTrack('Parent beforeUpdate');
  },
  updated() {
    addTrack('Parent updated');
  }
}
</script>

<style scoped>
.parent {
  position: relative;
  width: 200px;
  height: 200px;
  border: 3px solid blue;
  display: flex;
  align-items: center;
  justify-content: center;
}
.text {
  position: absolute;
  top: 0;
  left: 0;
}
</style>
