// src/vue/Track.vue
<template>
  <div class="track">
    <template v-for="track in tracks">
      <div class="trackItem" :key="Math.random()">{{ track }}</div>
    </template>
  </div>
</template>

<script>
import { getTracks, resetTracks } from './TrackContext';

export default {
  name: "Track",
  data() {
    return {
      tracks: []
    }
  },
  methods: {
    getTracks,
    resetTracks,
    updateTracks() {
      this.tracks = this.getTracks();
      this.$nextTick(() => {
        this.resetTracks();
      });
    }
  }
}
</script>

<style scoped>
.track {
  margin-top: 20px;
}
.trackItem {
  margin-bottom: 5px;
}
</style>

// src/react/Track.js
import React from 'react';

import { getTracks, resetTracks } from './TrackContext';

/**
 * https://reactjs.org/docs/react-component.html
 */
export default class Track extends React.Component {
  constructor(props) {
    super(props);
    this.state = {
      tracks: []
    };
  }
  updateTracks() {
    const tracks = getTracks();
    this.setState({ tracks }, () => {
      resetTracks();
    });
  }
  render() {
    return (
      <div style={Style.track}>
      {
        this.state.tracks.map((track) => {
          return <div style={Style.trackItem} key={Math.random()}>{track}</div>
        })
      }
      </div>
    );
  }
}

const Style = {
  track: {
    marginTop: 20
  },
  trackItem: {
    marginBottom: 5
  }
};
